# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: foreman-selinux.spec

# add or remove files that should be synced
files_to_sync:
    - foreman-selinux.spec
    - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: foreman-selinux
# downstream (Fedora) RPM package name
downstream_package_name: foreman-selinux

upstream_tag_template: "{version}"

actions:
  post-upstream-clone:
    - "wget https://raw.githubusercontent.com/theforeman/foreman-packaging/rpm/develop/packages/foreman/foreman-selinux/foreman-selinux.spec -O foreman-selinux.spec"
  get-current-version:
    - "sed 's/-develop//' VERSION"

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      rhel-8:
        additional_modules: "foreman:el8"
        additional_repos:
          - https://yum.theforeman.org/releases/nightly/el8/x86_64/
      rhel-9:
        additional_repos:
          - https://yum.theforeman.org/releases/nightly/el9/x86_64/
    module_hotfixes: true

srpm_build_deps:
  - wget
