#!/bin/bash

# relabel foreman
/sbin/restorecon -ri $* /usr/share/foreman \
  /var/lib/foreman \
  /var/run/foreman \
  /run/foreman \
  /run/foreman.sock \
  /var/log/foreman \
  /etc/foreman \
  /etc/puppet/node.rb \
  /etc/puppetlabs/puppet/node.rb \
  /etc/sysconfig/foreman* \
  /usr/lib/systemd/system/foreman* \
  /etc/systemd/system/foreman* \
  /etc/logrotate.d/foreman* \
  /etc/cron.d/foreman* \
  /usr/libexec/foreman \
  /usr/sbin/foreman-cockpit-session

exit 0
