#!/bin/bash

# relabel foreman
/sbin/restorecon -ri $* /usr/share/foreman \
  /usr/share/katello \
  /var/lib/foreman \
  /var/run/foreman \
  /run/foreman \
  /var/log/foreman \
  /etc/foreman \
  /etc/puppet/node.rb \
  /etc/sysconfig/foreman* \
  /etc/rc.d/init.d/foreman* \
  /etc/logrotate.d/foreman* \
  /etc/cron.d/foreman* \
  /usr/lib/ruby/gems/1.8/gems/passenger-* \
  /usr/lib64/gems/ruby/passenger-*/agents \
  /usr/lib64/ruby/site_ruby/1.8/x86_64-linux/agents \
  /var/run/rubygem-passenger

# relabel SCL mod_passenger and foreman plugins if SCL is found
[ -d /opt/theforeman/tfm/ ] && /sbin/restorecon -ri $* \
  /opt/theforeman/tfm/root/usr/share/gems/gems/passenger-* \
  /opt/theforeman/tfm/root/usr/lib64/gems/exts/passenger-*/agents \
  /opt/theforeman/tfm/root/usr/share/gems/gems/foreman*

exit 0
