---
name: Compile policy

on:
  - pull_request
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container:
          - "docker.io/almalinux:8"
          - "docker.io/almalinux:9"
          - "quay.io/centos/centos:stream9"
    container:
      image: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v4

      - name: Install SELinux
        run: yum install -y selinux-policy-devel policycoreutils bzip2 perl

      - name: Compile policy
        run: make

      - name: Check syntax of shell scripts
        run: bash -n *-relabel *-enable *-disable
