---
name: Compile policy

on:
  - pull_request
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        centos:
          - "7"
          - "stream8"
          - "stream9"
    container:
      image: quay.io/centos/centos:${{ matrix.centos }}

    steps:
      - uses: actions/checkout@v2

      - name: Install SELinux
        run: yum install -y selinux-policy-devel policycoreutils bzip2 perl

      - name: Install container-selinux
        run: dnf install -y container-selinux
        if: matrix.centos == 'stream8'

      - name: Compile policy
        run: make DISTRO=rhel$(rpm --eval '%rhel')

      - name: Check syntax of shell scripts
        run: bash -n *-relabel *-enable *-disable
